dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWD') }}"
      port: 5432
      dbname: stats_bg
      schema: bronze
      threads: 4