WITH 

ATTENDANCES AS (SELECT * FROM {{ source('bronze', 'ATTENDANCES') }}),
PLAYERS AS (SELECT * FROM {{ source('bronze', 'PLAYERS') }}),

FINAL AS (
    SELECT
        TO_DATE(A."DATE", '%dd%mm%YY') AS DATE,
        A."PLAYER_ID"::INT AS PLAYER_ID,
        P."NAME"::VARCHAR AS PLAYER_NAME,
        A."IS_HOST"::BOOLEAN AS IS_HOST
    FROM ATTENDANCES A
    LEFT JOIN PLAYERS P ON A."PLAYER_ID" = P."ID"
)

SELECT * FROM FINAL