WITH BG_CATEGORIES AS (
    SELECT
        CAST("GAME_ID" AS INTEGER) AS GAME_ID,
        CAST("CATEGORY_ID" AS INTEGER) AS CATEGORY_ID
    FROM {{ source('bronze', 'BG_CATEGORIES') }}        
)

SELECT * FROM BG_CATEGORIES