WITH BG_MECHANICS AS (
    SELECT
        CAST("GAME_ID" AS INTEGER) AS GAME_ID,
        CAST("MECHANIC_ID" AS INTEGER) AS MECHANIC_ID
    FROM {{ source('bronze', 'BG_MECHANICS') }}
)
SELECT * FROM BG_MECHANICS