WITH PLAYERS AS(
    SELECT
        "NAME"::VARCHAR AS NAME,
        "MEMBERSHIP"::CHAR AS MEMBERSHIP,
        "ID"::INTEGER AS ID,
        TO_DATE("LAST_DATE_ATTENDED", '%dd%mm%YY') AS LAST_DATE_ATTENDED
    FROM {{source('bronze', 'PLAYERS')}}
)

SELECT * FROM PLAYERS