WITH PLAYERS AS(
    SELECT
        CAST("NAME" AS VARCHAR) AS NAME,
        CAST("MEMBERSHIP" AS CHAR) AS MEMBERSHIP,
        CAST("ID" AS INTEGER) AS ID,
        TO_DATE("LAST_DATE_ATTENDED", '%dd%mm%YY') AS LAST_DATE_ATTENDED
    FROM {{source('bronze', 'PLAYERS')}}
)

SELECT * FROM PLAYERS