-- ADDICTED PLAYER OF THE YEAR
SELECT P."NAME", COUNT(DISTINCT A."DATE") AS TIMES_ATTENDED
FROM stats_bg.bronze."PLAYERS" P
LEFT JOIN stats_bg.bronze."ATTENDANCES" A ON P."ID" = A."PLAYER_ID" 
GROUP BY 1
ORDER BY 2 DESC