-- GROUP OF THE YEAR
WITH NAMES_GROUPED AS(
	SELECT STRING_AGG(P."NAME", ', ') AS GROUP_NAME, A."DATE"
	FROM stats_bg.bronze."PLAYERS" P
	LEFT JOIN stats_bg.bronze."ATTENDANCES" A ON P."ID" = A."PLAYER_ID"
	GROUP BY A."DATE"
)
SELECT GROUP_NAME, COUNT(DISTINCT "DATE") AS TIMES_REUNITED 
FROM NAMES_GROUPED
GROUP BY GROUP_NAME
ORDER BY TIMES_REUNITED DESC