-- HOST OF THE YEAR
SELECT P."NAME", COUNT(A."IS_HOST") AS TIMES_AS_HOST
FROM stats_bg.bronze."PLAYERS" P
LEFT JOIN stats_bg.bronze."ATTENDANCES" A ON P."ID" = A."PLAYER_ID"
WHERE A."IS_HOST"
GROUP BY 1
ORDER BY 2 DESC