-- MECHANIC OF THE YEAR
WITH DISTINCT_MATCHES AS (
	SELECT DISTINCT "ID", "GAME_ID" 
	FROM stats_bg.bronze."MATCHES"
)
SELECT M2."NAME", COUNT(BM."MECHANIC_ID") AS TOTAL_PLAYED
FROM DISTINCT_MATCHES M
LEFT JOIN stats_bg.bronze."BG_MECHANICS" BM ON M."GAME_ID" = BM."GAME_ID"
LEFT JOIN stats_bg.bronze."MECHANICS" M2 ON CAST(M2."ID" as INT) = BM."MECHANIC_ID" 
GROUP BY 1
ORDER BY 2 DESC